# -*- coding: utf-8 -*-
"""PasswordsStrength.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGxT8ADx0wl7Cwp18uwNKu_mdvll7sUT
"""

import re
v=input('Enter the password')
if(len(v)>=12):
  if(bool(re.match('((?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*]).{8,30})',v))==True):
    print('Password is strong')
  elif(bool(re.match('((*\d)(*[a-z])(*[A-Z])(*[!@#$%^&*]){8,30})',v))==True):
    print('Password is weak')
else:
  print('The password you have entered is invalid')